[meta]
name = "ManiaExchange"
author = "Greep"
category = "TMX"
perms = "paid"
siteid = 154

version = "1.0.2"

[script]
imports = [ "Icons.as", "Permissions.as", "Formatting.as", "Dialogs.as" ]

exports = [ "src/Exports/Exports.as" ]