[meta]
name = "ManiaExchange"
author = "Greep"
category = "TMX"
perms = "paid"
siteid = 154

version = "1.0.7"

[script]
imports = [ "Icons.as", "Permissions.as", "Formatting.as" ]
optional_dependencies = [ "BetterChat", "ItemExchange" ]

exports = [ "src/Exports/Exports.as" ]
timeout = 0

#defines = [ "FORCE_API_DOWN" ]
# FORCE_API_DOWN : Forces the API to be "down" after loading for tags and seasons.